Local network
Alexander-Ploskin/MathMechReposSemester4 pull request #19
Opened 2021-03-17 17:26 UTC by Alexander-Ploskin

2021-04-17 17:09 UTC, yurii-litvinov requested changes

2021-04-17 17:09 UTC, yurii-litvinov commented on HW5/LocalNetwork/LocalNetwork/Computer.fs
> +type Computer(os : OS, name : string) =
Надо комментарии

2021-04-17 17:09 UTC, yurii-litvinov commented on HW5/LocalNetwork/LocalNetwork/LocalNetwork.fs
> +            this.turn <| new Random()
Не надо Random каждый раз заново создавать, он по идее должен быть вообще один на всю программу (точнее, один на поток). Иначе, во-первых, все они, созданные в одну миллисекунду, будут одни значения возвращать, во-вторых, загаживать кучу своими трупиками :)

2021-04-17 17:09 UTC, yurii-litvinov commented on HW5/LocalNetwork/LocalNetwork/LocalNetwork.fs
> +                       if computer.Infected then computer.JustInfected <- true
Это Code Smell "Завистливый метод", тут больше обращений к состоянию Computer, чем к чему-либо ещё. И неспроста --- Computer играет роль Data Object-а, который и не функциональный (потому что мутабельный), и не объектно-ориентированный (потому что без собственного поведения). Я бы Computer дал существенно больше ответственности.

2021-04-17 17:09 UTC, yurii-litvinov commented on HW5/LocalNetwork/LocalNetwork/Virus.fs
> +    member val MacOSToLinux = 0.8 with get, set
Мне кажется, что это как-то проще можно было сделать, например, двумерным массивом хотя бы :)

2021-04-17 17:09 UTC, yurii-litvinov commented on HW5/LocalNetwork/LocalNetworkTests/LocalNetworkTests.fs
> +type MyRandom (x) =
Хочется всё-таки настоящих Mock-ов (типа Foq)

2021-04-18 08:23 UTC, Alexander-Ploskin commented on HW5/LocalNetwork/LocalNetwork/Virus.fs
> +    member val MacOSToLinux = 0.8 with get, set
Я думаю, оно не так уж и плохо выглядит, тем более, что я хочу, чтобы эти значения были как по умолчанию, так и с возможностью изменение во время работы. Проблема двумерного массива в том, что придется еще дополнительно держать каким-то образом шапку для него, тогда проще не получается.

2021-04-18 16:41 UTC, yurii-litvinov requested changes

2021-04-18 16:41 UTC, yurii-litvinov commented on HW5/LocalNetwork/LocalNetwork/Computer.fs
> +    member this.tryInfect(virus : Virus, random : Random) =
Методы, как обычно, именуются с заглавной

2021-04-18 16:41 UTC, yurii-litvinov commented on HW5/LocalNetwork/LocalNetwork/Computer.fs
> +    member val Name = name with get
Свойствам тоже бы комментарии. И я бы не стал делать столько сеттеров, и вообще, может, убрал бы большую их часть из public-свойств (например, JustInfected по идее влияет только на tryInfect и никому больше не нужно, но надо ещё иметь метод, который позволял бы его сбрасывать)

2021-04-18 16:41 UTC, yurii-litvinov commented on HW5/LocalNetwork/LocalNetwork/Virus.fs
> +    member val MacOSToLinux = 0.8 with get, set
Я, конечно, не согласен с Вашей аргументацией (потому что можно было сделать вместо N^2 свойств две функции, принимающие ОС "откуда" и ОС "куда", для получения и выставления значения --- как у Вас совсем не масштабируемо, а так ещё хоть как-то). Но хорошо, что она есть, это можно не править.

2021-04-22 15:48 UTC, merged