Powers of two
Alexander-Ploskin/MathMechReposSemester4 pull request #4
Opened 2021-02-14 14:00 UTC by Alexander-Ploskin

2021-02-15 13:01 UTC, yurii-litvinov requested changes
Надо немного поправить

2021-02-15 13:01 UTC, yurii-litvinov commented on HW1/PowersOfTwo/PowersOfTwo/Program.fs
> +    if (m < n) then raise(System.ArgumentException("lower border of the interval should be less than upper border"))
Это не совсем то, что просили в условии. Просили степени от n до m+n, то есть, например, getPowersOfTwo 2 1 должно было бы вернуть [4]

2021-02-15 13:01 UTC, yurii-litvinov commented on HW1/PowersOfTwo/PowersOfTwo/Program.fs
> +    List.fold (fun acc elem -> elem::acc) [] (loop result m)
Это библиотечный List.rev, если я правильно понимаю :)

2021-02-16 06:38 UTC, Alexander-Ploskin commented on HW1/PowersOfTwo/PowersOfTwo/Program.fs
> +    if (m < n) then raise(System.ArgumentException("lower border of the interval should be less than upper border"))
Если прям по условию, то [ 2^2; 2^(2+1) ] = [ 4; 8 ]

2021-02-16 09:49 UTC, yurii-litvinov commented on HW1/PowersOfTwo/PowersOfTwo/Program.fs
> +    if (m < n) then raise(System.ArgumentException("lower border of the interval should be less than upper border"))
Да, это правда :)

2021-02-16 09:51 UTC, yurii-litvinov approved these changes
Ага, зачтена

2021-02-16 09:51 UTC, yurii-litvinov commented on HW1/PowersOfTwo/PowersOfTwo/Program.fs
> +        elif (countdown <= n) then loop (List.map (fun x -> x * 2) acc) (countdown - 1)
Изначальное возведение в степень лучше было через pown сделать, а то тут за линейное время и долго.

2021-02-20 07:54 UTC, merged